In [73]:
drug_list = {
    "drug_name": ["paracetamol", 'amoxicillin', 'cefixime'],
    "common_strenght": ["500mg", '625mg', '200mg'],
    "drug_class": ["analgesic", 'bacterial infections', 'antibiotic']
}

In [74]:
import pandas as pd

In [75]:
df = pd.DataFrame(drug_list)

In [76]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [77]:
#df.set_index('drug_class', inplace=True)

In [78]:
#filt = (df['common_strenght'] == '500mg') | (df['drug_name'] == 'cefixime')

In [79]:
#df.loc[filt, 'drug_class']

In [80]:
#df.rename(columns={'drug_name':'drug', 'common_strength':'mg'})

In [81]:
df.loc[2] = ['cefixine', '250mg', 'antibiotic']

In [82]:
df.loc[2, ['common_strength', 'drug_class']] = ['200mg', 'ANTIBIOTIC']

In [83]:
df

     drug_name common_strenght            drug_class common_strength
0  paracetamol           500mg             analgesic             NaN
1  amoxicillin           625mg  bacterial infections             NaN
2     cefixine           250mg            ANTIBIOTIC           200mg

In [84]:
df.loc[2, 'common_strength'] = '350mg'

In [85]:
df

     drug_name common_strenght            drug_class common_strength
0  paracetamol           500mg             analgesic             NaN
1  amoxicillin           625mg  bacterial infections             NaN
2     cefixine           250mg            ANTIBIOTIC           350mg

In [86]:
df.at[2, 'common_strength'] = '200mg'

In [87]:
df

     drug_name common_strenght            drug_class common_strength
0  paracetamol           500mg             analgesic             NaN
1  amoxicillin           625mg  bacterial infections             NaN
2     cefixine           250mg            ANTIBIOTIC           200mg