In [1]:
drug_list = {
    "drug_name": ["paracetamol", 'amoxicillin', 'cefixime'],
    "common_strenght": ["500mg", '625mg', '200mg'],
    "drug_class": ["analgesic", 'bacterial infections', 'antibiotic']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(drug_list)

In [4]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [5]:
df['drug_class']

0               analgesic
1    bacterial infections
2              antibiotic
Name: drug_class, dtype: object

In [8]:
df.set_index('drug_class', inplace=True)

In [9]:
df

                        drug_name common_strenght
drug_class
analgesic             paracetamol           500mg
bacterial infections  amoxicillin           625mg
antibiotic               cefixime           200mg

In [10]:
df.index

Index(['analgesic', 'bacterial infections', 'antibiotic'], dtype='object', name='drug_class')

In [11]:
df.loc['antibiotic']

drug_name          cefixime
common_strenght       200mg
Name: antibiotic, dtype: object