In [4]:
drug = {
    "drug": "paracetamol",
    "common_strength": "500mg",
    "email": "analgesic"
}

In [5]:
drug_list = {
    "drug": ["paracetamol"],
    "common_strength": ["500mg"],
    "drug_class": ["analgesic"]
}

In [6]:
drug_list = {
    "drug_name": ["paracetamol", 'amoxicillin', 'cefixime'],
    "common_strenght": ["500mg", '625mg', '200mg'],
    "drug_class": ["analgesic", 'bacterial infections', 'antibiotic']
}

In [7]:
drug_list['drug_name']

['paracetamol', 'amoxicillin', 'cefixime']

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(drug_list)

In [10]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [12]:
df['drug_class']

0               analgesic
1    bacterial infections
2              antibiotic
Name: drug_class, dtype: object

In [14]:
df.drug_class

0               analgesic
1    bacterial infections
2              antibiotic
Name: drug_class, dtype: object

In [15]:
df[['drug_name', 'drug_class']]

     drug_name            drug_class
0  paracetamol             analgesic
1  amoxicillin  bacterial infections
2     cefixime            antibiotic

In [16]:
df.columns

Index(['drug_name', 'common_strenght', 'drug_class'], dtype='object')

In [17]:
df.iloc[[1,2], 2]

1    bacterial infections
2              antibiotic
Name: drug_class, dtype: object

In [43]:
df

     drug_name common_strenght            drug_class
0  paracetamol           500mg             analgesic
1  amoxicillin           625mg  bacterial infections
2     cefixime           200mg            antibiotic

In [20]:
df.loc[[0,1],['drug_class', 'common_strenght']]

             drug_class common_strenght
0             analgesic           500mg
1  bacterial infections           625mg